#
# makefile
#     Builds the Traits module.
#
# Author
#     Andy Brown <andybrown85@gmail.com>
#
MODULE = traits
CHILDREN = data
FILTER = 
GANDER = ../..
include $(GANDER)/globals.mak
include $(GANDER)/src/module.mak


# Altering
Applicable.hpp :

# Drawing
Identifiable.o : 
Drawable.o : Identifiable.o
Selectable.o : Drawable.o
