#
# makefile
#     Builds the Base module.
# 
# Author
#     Andrew Brown <adb1413@rit.edu>
#
MODULE = base
CHILDREN = data
FILTER = 
GANDER = ../..
include $(GANDER)/globals.mak
include $(GANDER)/src/module.mak


# Altering
Applicable.hpp :

# Drawing
Identifiable.o : 
Drawable.o : Identifiable.o
Selectable.o : Drawable.o
